name: Reconcile schemas repo

on:
  schedule:
    - cron: "0 2 * * *"

  # Optional manual trigger
  workflow_dispatch:

permissions:
  # no contents: write here because we use a PAT and not the usual GITHUB_TOKEN
  actions: read

jobs:
  bump-schema:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v6
        with:
          submodules: true
          fetch-depth: 0   # required for tagging + pushing
          # We MUST use a PAT here because Github does not let you chain events. E.g. an action triggered by CI will not trigger another pipeline.
          token: ${{ secrets.PAT_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
          always-auth: false

      - name: Configure git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Install deps
        run: npm ci
      - name: Bump Schema if there is an update and generate relevant commit / tag
        run: npx zx ./bumpSubmoduleAndVersion.ts
