name: Publish Package to npmjs

on: 
  push:
    tags:
      - '0.[0-9]+.[0-9]+'

permissions:
  id-token: write # Token is needed here for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0  
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install deps
        run: bun ci
      - name: Assert Tag matches Package.json Version
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          PKG_VERSION=$(bun -p "require('./package.json').version")
          [ "$TAG" = "$PKG_VERSION" ] || {
            echo "Tag ($TAG) does not match package.json version ($PKG_VERSION)"
            exit 1
          }
      - name: Build the package
        run: bun run ./generate.ts
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
      - name: Sanity check whoami
        run: npm whoami
      - name: Release the package
        run: npm publish
